#version: '3.8'
volumes:
  db:
    driver: local
services:
  db_postgres:
    image: postgres:15
    restart: always
    container_name: db_postgres
    command: postgres -c password_encryption=md5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--auth-local=md5"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    restart: always
    extra_hosts:
      - "il-hq-dc01.allot.local:172.17.0.55"
      - "artifactory.rdlab.local:10.110.12.24"
      - "bitbucket.rdlab.local:10.110.12.21"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock" #Add a Docker Host inside Jenkins
